#Service Registry Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone : http://localhost:2021/eureka
  instance:
    hostname: localhost
# Endpoints
microservice:
    ongole-banking:
      endpoints:
        endpoint:
          uri: http://ONGOLE-BANKING-FINANCIAL-SERVICES/v1/ongole/banking/financial/services/openOnlineAccount
          uri: http://ONGOLE-BANKING-FINANCIAL-SERVICES/v1/ongole/banking/financial/services/getAllCustomers
          uri: http://ONGOLE-BANKING-FINANCIAL-SERVICES/v1/ongole/banking/financial/services/findByCustomerId/{customerId}
          uri: http://ONGOLE-BANKING-FINANCIAL-SERVICES/v1/ongole/banking/financial/services/findByAccountNumber/{accountNumber}
          
    hyderabad-banking:
       endpoints:
        endpoint:
          uri: http://HYDERABAD-BANKING-FINANCIAL-SERVICES/v1/hyderabad/banking/financial/saveCustomer
          uri: http://HYDERABAD-BANKING-FINANCIAL-SERVICES/v1/hyderabad/banking/financial/openNewBankAccount
          uri: http://HYDERABAD-BANKING-FINANCIAL-SERVICES/v1/hyderabad/banking/financial/listClientCustomers
          uri: http://HYDERABAD-BANKING-FINANCIAL-SERVICES/v1/hyderabad/banking/financial/clientDetailsByAccountNumber/{accountNumber}
          uri: http://HYDERABAD-BANKING-FINANCIAL-SERVICES/v1/hyderabad/banking/financial/transferFunds
